[package]
name = "autotile"
version = "0.1.0"
authors = ["ruin <ipickering2@gmail.com>"]

[dependencies]
glium = "0.16.0"
glium_text = "0.11.0"
image = "0.13.0"
cgmath = "0.14.1"
rand = "0.3.15"
texture_packer = {version = "0.9.0", git = "https://github.com/Ruin0x11/texture_packer" }
